### ISSUE TITLE
Stanza generation shouldn’t be based on string concatenation

### ISSUE THREAD

**Issue by linkmauve** [movim/moxl#6]
XML is a quite complex specification, it would be for the best to delegate its serialization to an XML library everywhere it makes sense, especially when including other content inside of it, both for a security and an error reporting standpoint.

Modern server should reject any invalid XML, but in doing so they will abort the current stream which makes for a rather unpleasant user experience, and should never happen.

**Comment by edhelas** [comment]
I'm currently refactoring the whole part of the library related to that :) Be patient !

**Comment by edhelas** [comment]
It seems that all the XML sent by Movim are now generated. Closing this ticket :)
